apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer
  namespace: development
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development
  name: developer-role
rules:
# Full access to most resources
- apiGroups: ["", "apps", "batch"]
  resources: ["pods", "services", "deployments", "jobs", "cronjobs", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Read-only access to secrets
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]

# Access to logs
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]

# Access to exec (for debugging)
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-rolebinding
  namespace: development
subjects:
- kind: ServiceAccount
  name: developer
  namespace: development
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
