apiVersion: v1
kind: Pod
metadata:
  name: webapp-with-probes
  labels:
    app: webapp
spec:
  containers:
  - name: webapp
    image: nginx:1.21
    ports:
    - containerPort: 80
      name: http
    
    # Startup probe - for slow-starting applications
    # Gives app up to 5 minutes to start (30 * 10s)
    startupProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 30
    
    # Liveness probe - is the app alive?
    # Restarts container if fails
    livenessProbe:
      httpGet:
        path: /
        port: http
        httpHeaders:
        - name: Custom-Header
          value: Health-Check
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    
    # Readiness probe - is the app ready for traffic?
    # Removes from service if fails
    readinessProbe:
      httpGet:
        path: /
        port: http
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
