apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webapp-pvc
spec:
  accessModes:
    - ReadWriteOnce  # RWO - single node read-write
  
  resources:
    requests:
      storage: 5Gi
  
  storageClassName: standard  # Use default or specify storage class
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-with-storage
spec:
  replicas: 1  # RWO only allows 1 replica
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        volumeMounts:
        - name: webapp-storage
          mountPath: /usr/share/nginx/html
      
      volumes:
      - name: webapp-storage
        persistentVolumeClaim:
          claimName: webapp-pvc
