apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app: myapp
data:
  # Simple key-value pairs
  database_host: "postgres.default.svc.cluster.local"
  database_port: "5432"
  log_level: "info"
  
  # Configuration file
  app.properties: |
    server.port=8080
    server.host=0.0.0.0
    cache.enabled=true
    cache.ttl=3600
