apiVersion: apps/v1
kind: Deployment
metadata:
  name: versioned-deployment
  labels:
    app: versioned-app
  annotations:
    kubernetes.io/change-cause: "Initial deployment with nginx 1.21"
spec:
  replicas: 3
  
  # Keep last 10 revisions for rollback capability
  revisionHistoryLimit: 10
  
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # Zero downtime
      
  selector:
    matchLabels:
      app: versioned-app
      
  template:
    metadata:
      labels:
        app: versioned-app
        version: v1.0.0
    spec:
      containers:
      - name: app
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        
        # Health checks for safe rolling updates
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
