apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-deployment
  labels:
    app: webapp
spec:
  replicas: 5
  
  # Rolling update strategy
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2        # Create up to 2 extra pods during update
      maxUnavailable: 1  # At most 1 pod can be unavailable
      
  selector:
    matchLabels:
      app: webapp
      
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nginx:1.21
        ports:
        - containerPort: 80
        
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
