apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: webapp
    tier: frontend
spec:
  # Service selector - matches pods with these labels
  selector:
    app: webapp
    tier: frontend
    
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: production-only-service
  labels:
    app: webapp
    environment: production
spec:
  # This service only routes to production pods
  selector:
    app: webapp
    environment: production
    
  ports:
  - port: 80
    targetPort: 80
    
  type: ClusterIP
