apiVersion: v1
kind: Pod
metadata:
  name: pod-with-env
  labels:
    app: myapp
spec:
  containers:
  - name: app
    image: nginx:1.21
    ports:
    - containerPort: 80
    env:
    - name: ENVIRONMENT
      value: "production"
    - name: LOG_LEVEL
      value: "info"
    - name: DATABASE_URL
      value: "postgres://db:5432/mydb"
    - name: MAX_CONNECTIONS
      value: "100"
