apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    tier: frontend
spec:
  # Number of pod replicas to maintain
  replicas: 3
  
  # Selector to identify which pods belong to this ReplicaSet
  selector:
    matchLabels:
      app: nginx
      
  # Template for creating new pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
